CREATE TABLE IF NOT EXISTS users (

  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL,
  created_at TIMESTAMP,
  
  provider VARCHAR(50),
  provider_id VARCHAR(255),
  avatar_url VARCHAR(512)

);

CREATE TABLE IF NOT EXISTS user_repositories (

  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  repository_name VARCHAR(255) NOT NULL,
  webhook_configured BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

);
