CREATE TABLE IF NOT EXISTS users (

  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL,
  created_at TIMESTAMP,
  
  provider VARCHAR(50),
  provider_id VARCHAR(255),
  avatar_url VARCHAR(512)

);

CREATE TABLE IF NOT EXISTS user_repositories (

  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  repository_name VARCHAR(255) NOT NULL,
  webhook_configured BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

);

CREATE TABLE IF NOT EXISTS user_oauth_tokens (

  user_id BIGINT PRIMARY KEY,
  access_token TEXT NOT NULL,
  token_type VARCHAR(50),
  expires_at TIMESTAMP,
  refresh_token TEXT,
  refresh_token_expires_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

);

CREATE TABLE IF NOT EXISTS algorithm_records (

  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  problem_number VARCHAR(50) NOT NULL,
  title VARCHAR(255) NOT NULL,
  code LONGTEXT,
  language VARCHAR(50),
  platform VARCHAR(50) NOT NULL DEFAULT 'UNKNOWN',
  difficulty VARCHAR(50),
  runtime_ms INT,
  memory_kb INT,
  repository_name VARCHAR(255),
  file_path VARCHAR(512),
  commit_sha VARCHAR(100),
  commit_message TEXT,
  committed_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)

);

CREATE TABLE IF NOT EXISTS github_push_event (

  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  delivery_id VARCHAR(100) NOT NULL,
  repository_name VARCHAR(255) NOT NULL,
  ref VARCHAR(255) NOT NULL,
  head_commit_sha VARCHAR(100) NOT NULL,
  author_login VARCHAR(100),
  author_email VARCHAR(255),
  commit_message CLOB,
  files_json CLOB,
  raw_payload CLOB,
  status VARCHAR(20) NOT NULL,
  failure_reason CLOB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (delivery_id)

);

CREATE TABLE IF NOT EXISTS boards (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content CLOB NOT NULL,
  user_id BIGINT NOT NULL,
  algorithm_record_id BIGINT NULL,
  board_type VARCHAR(20) NOT NULL DEFAULT 'GENERAL',
  like_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  board_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  parent_id BIGINT NULL,
  line_number INT NULL,
  content CLOB NOT NULL,
  like_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS board_likes (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  board_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id),
  UNIQUE (board_id, user_id)
);

CREATE TABLE IF NOT EXISTS comment_likes (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  comment_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (comment_id) REFERENCES comments(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id),
  UNIQUE (comment_id, user_id)
);
